Testing test file

diff --git a/.github/workflows/code-critic.yaml b/.github/workflows/code-critic.yaml
--- a/.github/workflows/code-critic.yaml
+++ b/.github/workflows/code-critic.yaml
@@ -15,30 +15,30 @@ jobs:
         with:
           fetch-depth: 2
 
-      # - name: Install dependencies
-      #   run: |
-      #     python -m pip install --upgrade pip
-      #     pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-      # - name: Run GPT Code Critic
-      #   env:
-      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-      #   run: python3 main.py
+      - name: Run GPT Code Critic
+        env:
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+        run: python3 main.py
 
-      # - name: Check if results.sarif exists
-      #   run: |
-      #     if [ ! -f results.sarif ]; then
-      #       echo "::error::results.sarif not found"
-      #       exit 1
-      #     fi
+      - name: Check if results.sarif exists
+        run: |
+          if [ ! -f results.sarif ]; then
+            echo "::error::results.sarif not found"
+            exit 1
+          fi
 
       - name: Print results
         run: |
-          cat test.sarif
+          cat results.sarif
 
       - name: Upload results
         uses: github/codeql-action/upload-sarif@v2
         with:
-          sarif_file: test.sarif
+          sarif_file: results.sarif
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
